### ISSUE TITLE
"Communication error 100: Error completed" on FDR-x3000

### ISSUE THREAD

**Issue by Novex** [ma1co/OpenMemories-Launcher#2]
This is an odd one. I had the launcher installed on my FDR-x3000 (v1.00) and was loading apk's today to poke around the API's when the launcher stopped working. When trying to load it it would just go to a blank screen briefly and then back to the normal sony menu.

I tried to reinstall the launcher and ended up with the "Error completed":

```
>pmca-console install -f OpenMemories-Launcher-release-2.0.apk
Using drivers Windows-MSC, Windows-MTP
Looking for Sony devices

Querying MTP device
Sony Corporation FDR-X3000 is a camera in app install mode

Analyzing apk

Package: com.sony.imaging.app.livestreaming
Version: 2.0

Starting task
Starting communication
Uploading 0%
Uploading 100%
Downloading 100%
Installing 0%
Traceback (most recent call last):
  File "C:\projects\sony-pmca-re\pmca-console.py", line 96, in <module>
  File "C:\projects\sony-pmca-re\pmca-console.py", line 72, in main
  File "C:\projects\sony-pmca-re\pmca\commands\usb.py", line 291, in installCommand
  File "C:\projects\sony-pmca-re\pmca\commands\usb.py", line 86, in installApp
Exception: Communication error 100: Error completed
[1596] Failed to execute script pmca-console
```

I've tried:
* A factory reset, but the same issue still occurred (the ustream app didn't get replaced).
* Restoring to an original backup of my `nflasha17` through updatershell (which mostly deleted files in the `/app` and `/lib` directories)
  * This has brought back the original ustream app, but I still can't reinstall the launcher over the top of it
* Updating to FW 1.01, this didn't change anything either

I'm not sure what to try now as my old `nflasha` dumps pretty much match my current `nflasha` dumps and it's still not working - any ideas for other things to look at/ways to completely reset the state of the system?

**Comment by Novex** [comment]
Ok I managed to get the launcher installed again by using the master version of `pmca-console` and using the new updatershell install command, like so:

```
>python pmca-console.py updatershell
Using drivers Windows-MSC, Windows-MTP
Looking for Sony devices

Querying mass storage device
Sony Camcorder is a camera in mass storage mode

Getting device info
Using firmware for model FDR-X3000

Initializing firmware update
Switching to updater mode

Waiting for camera to switch...
Please follow the instructions on the camera screen.
Initializing firmware update
Writing firmware
0%
100%
Starting updater shell...

Welcome to the USB debug shell.
Type `help` for the list of supported commands.
Type `exit` to quit.
>install OpenMemories-Launcher-release-2.0.apk
>exit
Done
```

I'm not sure exactly how it differs from `pmca-console install`, but everything seems to be working again so far :tada:

**Comment by andrusz** [comment]
Had the same issue with AS200V, installation is working when running from updatershell, not using command line install.
